version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/proxy_params:/etc/nginx/proxy_params
    networks:
      - gr8-shared-network

networks:
  gr8-shared-network:
    external: true
