
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./static/default.conf:/etc/nginx/conf.d/default.conf
      - matomo-data:/var/www/html
    networks:
      - gr8-shared-network

  matomo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8083:80"
    volumes:
      - matomo-data:/var/www/html
      - ./static/config.ini.php:/var/www/html/config/config.ini.php
    environment:
      MATOMO_DATABASE_HOST: ${MATOMO_DATABASE_HOST}
      MATOMO_DATABASE_ADAPTER: mysqli
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_TABLES_PREFIX}
      MATOMO_DATABASE_USERNAME: ${MATOMO_DATABASE_USERNAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DATABASE_DBNAME: ${MATOMO_DATABASE_DBNAME}
      MATOMO_CONFIG_SALT: ${MATOMO_CONFIG_SALT}
    networks:
      - gr8-shared-network

  db:
    image: mysql:5.7
    command: --max-allowed-packet=64MB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MATOMO_DATABASE_DBNAME}
      MYSQL_USER: ${MATOMO_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - gr8-shared-network

volumes:
  matomo-data:
  db-data:

networks:
  gr8-shared-network:
    external: true
